# Generated by Django 5.2.3 on 2025-06-21 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('licencia', 'licencia de conduccion'), ('SOAT', 'SOAT'), ('RTM', 'Revision técnico-mecánica')], max_length=20)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('fecha_vencimiento', models.DateField()),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='conductores.conductor')),
            ],
        ),
    ]
