# Generated by Django 5.2.3 on 2025-06-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('licencia', 'Licencia de conducción'), ('SOAT', 'SOAT'), ('RTM', 'Revisión técnico-mecánica')], max_length=20),
        ),
    ]
