# Generated by Django 5.2.5 on 2025-08-22 22:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0004_alter_conductor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='fecha_subida',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
