# Generated by Django 5.2.5 on 2025-08-22 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0005_documento_fecha_subida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='fecha_subida',
        ),
    ]
