# Generated by Django 5.2.5 on 2025-08-22 23:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0006_remove_documento_fecha_subida'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='fecha_subida',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
