# Generated by Django 5.2.5 on 2025-08-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0007_documento_fecha_subida'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='nombre',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_subida',
            field=models.DateField(auto_now_add=True),
        ),
    ]
