# Generated by Django 5.2.5 on 2025-09-12 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_remove_reseña_cliente_remove_reseña_conductor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialAcciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(choices=[('crear_usuario', 'Crear Usuario'), ('eliminar_usuario', 'Eliminar Usuario'), ('aprobar_validador', 'Aprobar Validador'), ('rechazar_validador', 'Rechazar Validador'), ('ver_reportes', 'Ver Reportes')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('admin_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_afectado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Acciones',
                'verbose_name_plural': 'Historial de Acciones',
            },
        ),
        migrations.CreateModel(
            name='RegistroPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password_hash', models.CharField(max_length=128)),
                ('rol_solicitado', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_decision', models.DateTimeField(blank=True, null=True)),
                ('razon_rechazo', models.TextField(blank=True)),
                ('decidido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro Pendiente',
                'verbose_name_plural': 'Registros Pendientes',
            },
        ),
    ]
